# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_debug.ui'
#
# Created: Wed Jul  6 14:11:27 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.tabMenu = QtWidgets.QTabWidget(self.centralWidget)
        self.tabMenu.setGeometry(QtCore.QRect(0, 0, 481, 740))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMenu.sizePolicy().hasHeightForWidth())
        self.tabMenu.setSizePolicy(sizePolicy)
        self.tabMenu.setObjectName("tabMenu")
        self.ControlTab = QtWidgets.QWidget()
        self.ControlTab.setObjectName("ControlTab")
        self.btnEstop = QtWidgets.QPushButton(self.ControlTab)
        self.btnEstop.setGeometry(QtCore.QRect(340, 470, 121, 221))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btnEstop.setFont(font)
        self.btnEstop.setDefault(True)
        self.btnEstop.setObjectName("btnEstop")
        self.boxSetTarget = QtWidgets.QGroupBox(self.ControlTab)
        self.boxSetTarget.setGeometry(QtCore.QRect(0, 0, 321, 700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxSetTarget.sizePolicy().hasHeightForWidth())
        self.boxSetTarget.setSizePolicy(sizePolicy)
        self.boxSetTarget.setObjectName("boxSetTarget")
        self.labelFilament = QtWidgets.QLabel(self.boxSetTarget)
        self.labelFilament.setGeometry(QtCore.QRect(10, 50, 80, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelFilament.setFont(font)
        self.labelFilament.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFilament.setWordWrap(True)
        self.labelFilament.setObjectName("labelFilament")
        self.labelAircon = QtWidgets.QLabel(self.boxSetTarget)
        self.labelAircon.setGeometry(QtCore.QRect(10, 150, 80, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelAircon.setFont(font)
        self.labelAircon.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAircon.setWordWrap(True)
        self.labelAircon.setObjectName("labelAircon")
        self.labelColdblock = QtWidgets.QLabel(self.boxSetTarget)
        self.labelColdblock.setGeometry(QtCore.QRect(10, 260, 80, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelColdblock.setFont(font)
        self.labelColdblock.setAlignment(QtCore.Qt.AlignCenter)
        self.labelColdblock.setWordWrap(True)
        self.labelColdblock.setObjectName("labelColdblock")
        self.labelHotend = QtWidgets.QLabel(self.boxSetTarget)
        self.labelHotend.setGeometry(QtCore.QRect(10, 370, 80, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelHotend.setFont(font)
        self.labelHotend.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHotend.setWordWrap(True)
        self.labelHotend.setObjectName("labelHotend")
        self.labelFeedrate = QtWidgets.QLabel(self.boxSetTarget)
        self.labelFeedrate.setGeometry(QtCore.QRect(10, 480, 80, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelFeedrate.setFont(font)
        self.labelFeedrate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFeedrate.setWordWrap(True)
        self.labelFeedrate.setObjectName("labelFeedrate")
        self.lcdFeedrate = QtWidgets.QLCDNumber(self.boxSetTarget)
        self.lcdFeedrate.setGeometry(QtCore.QRect(90, 460, 120, 100))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdFeedrate.setFont(font)
        self.lcdFeedrate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdFeedrate.setAutoFillBackground(True)
        self.lcdFeedrate.setSmallDecimalPoint(False)
        self.lcdFeedrate.setDigitCount(5)
        self.lcdFeedrate.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdFeedrate.setProperty("value", 5.0)
        self.lcdFeedrate.setObjectName("lcdFeedrate")
        self.lcdFilament = QtWidgets.QLCDNumber(self.boxSetTarget)
        self.lcdFilament.setGeometry(QtCore.QRect(90, 20, 120, 100))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdFilament.setFont(font)
        self.lcdFilament.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdFilament.setAutoFillBackground(True)
        self.lcdFilament.setSmallDecimalPoint(False)
        self.lcdFilament.setDigitCount(5)
        self.lcdFilament.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdFilament.setProperty("value", 1.75)
        self.lcdFilament.setObjectName("lcdFilament")
        self.lcdcoldblock = QtWidgets.QLCDNumber(self.boxSetTarget)
        self.lcdcoldblock.setGeometry(QtCore.QRect(90, 240, 120, 100))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdcoldblock.setFont(font)
        self.lcdcoldblock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdcoldblock.setAutoFillBackground(True)
        self.lcdcoldblock.setSmallDecimalPoint(False)
        self.lcdcoldblock.setDigitCount(5)
        self.lcdcoldblock.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdcoldblock.setProperty("value", 25.1)
        self.lcdcoldblock.setObjectName("lcdcoldblock")
        self.lcdAircon = QtWidgets.QLCDNumber(self.boxSetTarget)
        self.lcdAircon.setGeometry(QtCore.QRect(90, 130, 120, 100))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdAircon.setFont(font)
        self.lcdAircon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdAircon.setAutoFillBackground(True)
        self.lcdAircon.setSmallDecimalPoint(False)
        self.lcdAircon.setDigitCount(5)
        self.lcdAircon.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdAircon.setProperty("value", 25.1)
        self.lcdAircon.setObjectName("lcdAircon")
        self.lcdHotend = QtWidgets.QLCDNumber(self.boxSetTarget)
        self.lcdHotend.setGeometry(QtCore.QRect(90, 350, 120, 100))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdHotend.setFont(font)
        self.lcdHotend.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdHotend.setAutoFillBackground(True)
        self.lcdHotend.setSmallDecimalPoint(False)
        self.lcdHotend.setDigitCount(5)
        self.lcdHotend.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdHotend.setProperty("value", 25.1)
        self.lcdHotend.setObjectName("lcdHotend")
        self.scrollFeedrate = QtWidgets.QScrollBar(self.boxSetTarget)
        self.scrollFeedrate.setGeometry(QtCore.QRect(220, 460, 40, 100))
        self.scrollFeedrate.setAutoFillBackground(False)
        self.scrollFeedrate.setMinimum(1)
        self.scrollFeedrate.setMaximum(50)
        self.scrollFeedrate.setPageStep(1)
        self.scrollFeedrate.setProperty("value", 5)
        self.scrollFeedrate.setSliderPosition(5)
        self.scrollFeedrate.setOrientation(QtCore.Qt.Vertical)
        self.scrollFeedrate.setInvertedAppearance(False)
        self.scrollFeedrate.setInvertedControls(True)
        self.scrollFeedrate.setObjectName("scrollFeedrate")
        self.scrollHotend = QtWidgets.QScrollBar(self.boxSetTarget)
        self.scrollHotend.setGeometry(QtCore.QRect(220, 350, 40, 100))
        self.scrollHotend.setAutoFillBackground(False)
        self.scrollHotend.setMinimum(251)
        self.scrollHotend.setMaximum(1500)
        self.scrollHotend.setPageStep(1)
        self.scrollHotend.setSliderPosition(251)
        self.scrollHotend.setOrientation(QtCore.Qt.Vertical)
        self.scrollHotend.setInvertedAppearance(False)
        self.scrollHotend.setInvertedControls(True)
        self.scrollHotend.setObjectName("scrollHotend")
        self.scrollColdblock = QtWidgets.QScrollBar(self.boxSetTarget)
        self.scrollColdblock.setGeometry(QtCore.QRect(220, 240, 40, 100))
        self.scrollColdblock.setAutoFillBackground(False)
        self.scrollColdblock.setMinimum(150)
        self.scrollColdblock.setMaximum(300)
        self.scrollColdblock.setPageStep(1)
        self.scrollColdblock.setSliderPosition(251)
        self.scrollColdblock.setOrientation(QtCore.Qt.Vertical)
        self.scrollColdblock.setInvertedAppearance(False)
        self.scrollColdblock.setInvertedControls(True)
        self.scrollColdblock.setObjectName("scrollColdblock")
        self.scrollAircon = QtWidgets.QScrollBar(self.boxSetTarget)
        self.scrollAircon.setGeometry(QtCore.QRect(220, 130, 40, 100))
        self.scrollAircon.setAutoFillBackground(False)
        self.scrollAircon.setMinimum(150)
        self.scrollAircon.setMaximum(300)
        self.scrollAircon.setPageStep(1)
        self.scrollAircon.setSliderPosition(251)
        self.scrollAircon.setOrientation(QtCore.Qt.Vertical)
        self.scrollAircon.setInvertedAppearance(False)
        self.scrollAircon.setInvertedControls(True)
        self.scrollAircon.setObjectName("scrollAircon")
        self.scrollFilament = QtWidgets.QScrollBar(self.boxSetTarget)
        self.scrollFilament.setGeometry(QtCore.QRect(220, 20, 40, 100))
        self.scrollFilament.setAutoFillBackground(False)
        self.scrollFilament.setMinimum(160)
        self.scrollFilament.setMaximum(210)
        self.scrollFilament.setPageStep(1)
        self.scrollFilament.setSliderPosition(175)
        self.scrollFilament.setOrientation(QtCore.Qt.Vertical)
        self.scrollFilament.setInvertedAppearance(False)
        self.scrollFilament.setInvertedControls(True)
        self.scrollFilament.setObjectName("scrollFilament")
        self.btnONAircon = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnONAircon.setGeometry(QtCore.QRect(260, 140, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnONAircon.setFont(font)
        self.btnONAircon.setObjectName("btnONAircon")
        self.btnRetract = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnRetract.setGeometry(QtCore.QRect(170, 570, 140, 120))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btnRetract.setFont(font)
        self.btnRetract.setObjectName("btnRetract")
        self.btnExtrude = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnExtrude.setGeometry(QtCore.QRect(10, 570, 140, 120))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btnExtrude.setFont(font)
        self.btnExtrude.setAutoDefault(False)
        self.btnExtrude.setDefault(False)
        self.btnExtrude.setFlat(False)
        self.btnExtrude.setObjectName("btnExtrude")
        self.btnOFFAircon = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnOFFAircon.setGeometry(QtCore.QRect(260, 180, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnOFFAircon.setFont(font)
        self.btnOFFAircon.setObjectName("btnOFFAircon")
        self.btnONColdblock = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnONColdblock.setGeometry(QtCore.QRect(260, 250, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnONColdblock.setFont(font)
        self.btnONColdblock.setObjectName("btnONColdblock")
        self.btnOFFColdblock = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnOFFColdblock.setGeometry(QtCore.QRect(260, 290, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnOFFColdblock.setFont(font)
        self.btnOFFColdblock.setObjectName("btnOFFColdblock")
        self.btnONHotend = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnONHotend.setGeometry(QtCore.QRect(260, 360, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnONHotend.setFont(font)
        self.btnONHotend.setObjectName("btnONHotend")
        self.btnOFFHotend = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnOFFHotend.setGeometry(QtCore.QRect(260, 400, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnOFFHotend.setFont(font)
        self.btnOFFHotend.setObjectName("btnOFFHotend")
        self.boxSensersReading = QtWidgets.QGroupBox(self.ControlTab)
        self.boxSensersReading.setGeometry(QtCore.QRect(320, 0, 151, 461))
        self.boxSensersReading.setObjectName("boxSensersReading")
        self.labelReadAircon = QtWidgets.QLabel(self.boxSensersReading)
        self.labelReadAircon.setGeometry(QtCore.QRect(30, 160, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.labelReadAircon.setFont(font)
        self.labelReadAircon.setAlignment(QtCore.Qt.AlignCenter)
        self.labelReadAircon.setObjectName("labelReadAircon")
        self.labelReadColdblock = QtWidgets.QLabel(self.boxSensersReading)
        self.labelReadColdblock.setGeometry(QtCore.QRect(30, 270, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.labelReadColdblock.setFont(font)
        self.labelReadColdblock.setAlignment(QtCore.Qt.AlignCenter)
        self.labelReadColdblock.setObjectName("labelReadColdblock")
        self.labelReadHotend = QtWidgets.QLabel(self.boxSensersReading)
        self.labelReadHotend.setGeometry(QtCore.QRect(30, 380, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.labelReadHotend.setFont(font)
        self.labelReadHotend.setAlignment(QtCore.Qt.AlignCenter)
        self.labelReadHotend.setObjectName("labelReadHotend")
        self.tabMenu.addTab(self.ControlTab, "")
        self.CameraTab = QtWidgets.QWidget()
        self.CameraTab.setObjectName("CameraTab")
        self.labelPic1 = QtWidgets.QLabel(self.CameraTab)
        self.labelPic1.setGeometry(QtCore.QRect(10, 10, 100, 400))
        self.labelPic1.setText("")
        self.labelPic1.setPixmap(QtGui.QPixmap("../../../../../Public/Pictures/Sample Pictures/Desert.jpg"))
        self.labelPic1.setObjectName("labelPic1")
        self.labelPic2 = QtWidgets.QLabel(self.CameraTab)
        self.labelPic2.setGeometry(QtCore.QRect(130, 10, 100, 400))
        self.labelPic2.setText("")
        self.labelPic2.setPixmap(QtGui.QPixmap("../../../../../Public/Pictures/Sample Pictures/Desert.jpg"))
        self.labelPic2.setObjectName("labelPic2")
        self.labelPic3 = QtWidgets.QLabel(self.CameraTab)
        self.labelPic3.setGeometry(QtCore.QRect(250, 10, 100, 400))
        self.labelPic3.setText("")
        self.labelPic3.setPixmap(QtGui.QPixmap("../../../../../Public/Pictures/Sample Pictures/Desert.jpg"))
        self.labelPic3.setObjectName("labelPic3")
        self.labelPic4 = QtWidgets.QLabel(self.CameraTab)
        self.labelPic4.setGeometry(QtCore.QRect(370, 10, 100, 400))
        self.labelPic4.setText("")
        self.labelPic4.setPixmap(QtGui.QPixmap("../../../../../Public/Pictures/Sample Pictures/Desert.jpg"))
        self.labelPic4.setObjectName("labelPic4")
        self.scrollControl1 = QtWidgets.QScrollBar(self.CameraTab)
        self.scrollControl1.setGeometry(QtCore.QRect(30, 440, 20, 200))
        self.scrollControl1.setMaximum(100)
        self.scrollControl1.setProperty("value", 50)
        self.scrollControl1.setOrientation(QtCore.Qt.Vertical)
        self.scrollControl1.setInvertedControls(False)
        self.scrollControl1.setObjectName("scrollControl1")
        self.scrollControl2 = QtWidgets.QScrollBar(self.CameraTab)
        self.scrollControl2.setGeometry(QtCore.QRect(80, 440, 20, 200))
        self.scrollControl2.setMaximum(100)
        self.scrollControl2.setProperty("value", 50)
        self.scrollControl2.setOrientation(QtCore.Qt.Vertical)
        self.scrollControl2.setInvertedControls(False)
        self.scrollControl2.setObjectName("scrollControl2")
        self.scrollControl3 = QtWidgets.QScrollBar(self.CameraTab)
        self.scrollControl3.setGeometry(QtCore.QRect(130, 440, 20, 200))
        self.scrollControl3.setMaximum(100)
        self.scrollControl3.setProperty("value", 50)
        self.scrollControl3.setOrientation(QtCore.Qt.Vertical)
        self.scrollControl3.setInvertedControls(False)
        self.scrollControl3.setObjectName("scrollControl3")
        self.scrollControl4 = QtWidgets.QScrollBar(self.CameraTab)
        self.scrollControl4.setGeometry(QtCore.QRect(180, 440, 20, 200))
        self.scrollControl4.setMaximum(100)
        self.scrollControl4.setProperty("value", 50)
        self.scrollControl4.setOrientation(QtCore.Qt.Vertical)
        self.scrollControl4.setInvertedControls(False)
        self.scrollControl4.setObjectName("scrollControl4")
        self.scrollControl5 = QtWidgets.QScrollBar(self.CameraTab)
        self.scrollControl5.setGeometry(QtCore.QRect(230, 440, 20, 200))
        self.scrollControl5.setMaximum(100)
        self.scrollControl5.setProperty("value", 50)
        self.scrollControl5.setOrientation(QtCore.Qt.Vertical)
        self.scrollControl5.setInvertedControls(False)
        self.scrollControl5.setObjectName("scrollControl5")
        self.scrollControl6 = QtWidgets.QScrollBar(self.CameraTab)
        self.scrollControl6.setGeometry(QtCore.QRect(280, 440, 20, 200))
        self.scrollControl6.setMaximum(100)
        self.scrollControl6.setProperty("value", 50)
        self.scrollControl6.setOrientation(QtCore.Qt.Vertical)
        self.scrollControl6.setInvertedControls(False)
        self.scrollControl6.setObjectName("scrollControl6")
        self.scrollControl7 = QtWidgets.QScrollBar(self.CameraTab)
        self.scrollControl7.setGeometry(QtCore.QRect(330, 440, 20, 200))
        self.scrollControl7.setMaximum(100)
        self.scrollControl7.setProperty("value", 50)
        self.scrollControl7.setOrientation(QtCore.Qt.Vertical)
        self.scrollControl7.setInvertedControls(False)
        self.scrollControl7.setObjectName("scrollControl7")
        self.scrollControl8 = QtWidgets.QScrollBar(self.CameraTab)
        self.scrollControl8.setGeometry(QtCore.QRect(380, 440, 20, 200))
        self.scrollControl8.setMaximum(100)
        self.scrollControl8.setProperty("value", 50)
        self.scrollControl8.setOrientation(QtCore.Qt.Vertical)
        self.scrollControl8.setInvertedControls(False)
        self.scrollControl8.setObjectName("scrollControl8")
        self.scrollControl9 = QtWidgets.QScrollBar(self.CameraTab)
        self.scrollControl9.setGeometry(QtCore.QRect(430, 440, 20, 200))
        self.scrollControl9.setMaximum(100)
        self.scrollControl9.setProperty("value", 50)
        self.scrollControl9.setOrientation(QtCore.Qt.Vertical)
        self.scrollControl9.setInvertedControls(False)
        self.scrollControl9.setObjectName("scrollControl9")
        self.labelControl1 = QtWidgets.QLabel(self.CameraTab)
        self.labelControl1.setGeometry(QtCore.QRect(10, 640, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.labelControl1.setFont(font)
        self.labelControl1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelControl1.setWordWrap(True)
        self.labelControl1.setObjectName("labelControl1")
        self.labelControl2 = QtWidgets.QLabel(self.CameraTab)
        self.labelControl2.setGeometry(QtCore.QRect(60, 640, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.labelControl2.setFont(font)
        self.labelControl2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelControl2.setWordWrap(True)
        self.labelControl2.setObjectName("labelControl2")
        self.labelControl3 = QtWidgets.QLabel(self.CameraTab)
        self.labelControl3.setGeometry(QtCore.QRect(110, 640, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.labelControl3.setFont(font)
        self.labelControl3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelControl3.setWordWrap(True)
        self.labelControl3.setObjectName("labelControl3")
        self.labelControl4 = QtWidgets.QLabel(self.CameraTab)
        self.labelControl4.setGeometry(QtCore.QRect(160, 640, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.labelControl4.setFont(font)
        self.labelControl4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelControl4.setWordWrap(True)
        self.labelControl4.setObjectName("labelControl4")
        self.labelControl5 = QtWidgets.QLabel(self.CameraTab)
        self.labelControl5.setGeometry(QtCore.QRect(210, 640, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.labelControl5.setFont(font)
        self.labelControl5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelControl5.setWordWrap(True)
        self.labelControl5.setObjectName("labelControl5")
        self.labelControl6 = QtWidgets.QLabel(self.CameraTab)
        self.labelControl6.setGeometry(QtCore.QRect(260, 640, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.labelControl6.setFont(font)
        self.labelControl6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelControl6.setWordWrap(True)
        self.labelControl6.setObjectName("labelControl6")
        self.labelControl7 = QtWidgets.QLabel(self.CameraTab)
        self.labelControl7.setGeometry(QtCore.QRect(310, 640, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.labelControl7.setFont(font)
        self.labelControl7.setAlignment(QtCore.Qt.AlignCenter)
        self.labelControl7.setWordWrap(True)
        self.labelControl7.setObjectName("labelControl7")
        self.labelControl8 = QtWidgets.QLabel(self.CameraTab)
        self.labelControl8.setGeometry(QtCore.QRect(360, 640, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.labelControl8.setFont(font)
        self.labelControl8.setAlignment(QtCore.Qt.AlignCenter)
        self.labelControl8.setWordWrap(True)
        self.labelControl8.setObjectName("labelControl8")
        self.labelControl9 = QtWidgets.QLabel(self.CameraTab)
        self.labelControl9.setGeometry(QtCore.QRect(410, 640, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.labelControl9.setFont(font)
        self.labelControl9.setAlignment(QtCore.Qt.AlignCenter)
        self.labelControl9.setWordWrap(True)
        self.labelControl9.setObjectName("labelControl9")
        self.tabMenu.addTab(self.CameraTab, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setEnabled(False)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabMenu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnEstop.setText(_translate("MainWindow", "E-Stop"))
        self.boxSetTarget.setTitle(_translate("MainWindow", "User Input and Set Target"))
        self.labelFilament.setText(_translate("MainWindow", "Filament Diameter"))
        self.labelAircon.setText(_translate("MainWindow", "Aircon"))
        self.labelColdblock.setText(_translate("MainWindow", "ColdBlock"))
        self.labelHotend.setText(_translate("MainWindow", "HotEnd"))
        self.labelFeedrate.setText(_translate("MainWindow", "Feedrate"))
        self.btnONAircon.setText(_translate("MainWindow", "On"))
        self.btnRetract.setText(_translate("MainWindow", "Retract"))
        self.btnExtrude.setText(_translate("MainWindow", "Extrude"))
        self.btnOFFAircon.setText(_translate("MainWindow", "Off"))
        self.btnONColdblock.setText(_translate("MainWindow", "On"))
        self.btnOFFColdblock.setText(_translate("MainWindow", "Off"))
        self.btnONHotend.setText(_translate("MainWindow", "On"))
        self.btnOFFHotend.setText(_translate("MainWindow", "Off"))
        self.boxSensersReading.setTitle(_translate("MainWindow", "Sensors Reading"))
        self.labelReadAircon.setText(_translate("MainWindow", "30.0C"))
        self.labelReadColdblock.setText(_translate("MainWindow", "30.0C"))
        self.labelReadHotend.setText(_translate("MainWindow", "30.0C"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.ControlTab), _translate("MainWindow", "Control"))
        self.labelControl1.setText(_translate("MainWindow", "Crtl1"))
        self.labelControl2.setText(_translate("MainWindow", "Crtl2"))
        self.labelControl3.setText(_translate("MainWindow", "Crtl3"))
        self.labelControl4.setText(_translate("MainWindow", "Crtl4"))
        self.labelControl5.setText(_translate("MainWindow", "Crtl5"))
        self.labelControl6.setText(_translate("MainWindow", "Crtl6"))
        self.labelControl7.setText(_translate("MainWindow", "Crtl7"))
        self.labelControl8.setText(_translate("MainWindow", "Ctrl8"))
        self.labelControl9.setText(_translate("MainWindow", "Crtl9"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.CameraTab), _translate("MainWindow", "Camera"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

