# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_debug.ui'
#
# Created: Sat Jul  9 15:27:27 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.tabMenu = QtWidgets.QTabWidget(self.centralWidget)
        self.tabMenu.setGeometry(QtCore.QRect(0, 0, 480, 720))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMenu.sizePolicy().hasHeightForWidth())
        self.tabMenu.setSizePolicy(sizePolicy)
        self.tabMenu.setObjectName("tabMenu")
        self.ControlTab = QtWidgets.QWidget()
        self.ControlTab.setObjectName("ControlTab")
        self.btnEstop = QtWidgets.QPushButton(self.ControlTab)
        self.btnEstop.setGeometry(QtCore.QRect(340, 470, 121, 221))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btnEstop.setFont(font)
        self.btnEstop.setDefault(True)
        self.btnEstop.setObjectName("btnEstop")
        self.boxSetTarget = QtWidgets.QGroupBox(self.ControlTab)
        self.boxSetTarget.setGeometry(QtCore.QRect(0, 0, 321, 700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxSetTarget.sizePolicy().hasHeightForWidth())
        self.boxSetTarget.setSizePolicy(sizePolicy)
        self.boxSetTarget.setObjectName("boxSetTarget")
        self.labelFilament = QtWidgets.QLabel(self.boxSetTarget)
        self.labelFilament.setGeometry(QtCore.QRect(10, 50, 80, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelFilament.setFont(font)
        self.labelFilament.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFilament.setWordWrap(True)
        self.labelFilament.setObjectName("labelFilament")
        self.labelAircon = QtWidgets.QLabel(self.boxSetTarget)
        self.labelAircon.setGeometry(QtCore.QRect(10, 150, 80, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelAircon.setFont(font)
        self.labelAircon.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAircon.setWordWrap(True)
        self.labelAircon.setObjectName("labelAircon")
        self.labelColdblock = QtWidgets.QLabel(self.boxSetTarget)
        self.labelColdblock.setGeometry(QtCore.QRect(10, 260, 80, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelColdblock.setFont(font)
        self.labelColdblock.setAlignment(QtCore.Qt.AlignCenter)
        self.labelColdblock.setWordWrap(True)
        self.labelColdblock.setObjectName("labelColdblock")
        self.labelHotend = QtWidgets.QLabel(self.boxSetTarget)
        self.labelHotend.setGeometry(QtCore.QRect(10, 370, 80, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelHotend.setFont(font)
        self.labelHotend.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHotend.setWordWrap(True)
        self.labelHotend.setObjectName("labelHotend")
        self.labelFeedrate = QtWidgets.QLabel(self.boxSetTarget)
        self.labelFeedrate.setGeometry(QtCore.QRect(10, 480, 80, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelFeedrate.setFont(font)
        self.labelFeedrate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFeedrate.setWordWrap(True)
        self.labelFeedrate.setObjectName("labelFeedrate")
        self.lcdFeedrate = QtWidgets.QLCDNumber(self.boxSetTarget)
        self.lcdFeedrate.setGeometry(QtCore.QRect(90, 460, 120, 100))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdFeedrate.setFont(font)
        self.lcdFeedrate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdFeedrate.setAutoFillBackground(True)
        self.lcdFeedrate.setSmallDecimalPoint(False)
        self.lcdFeedrate.setDigitCount(5)
        self.lcdFeedrate.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdFeedrate.setProperty("value", 5.0)
        self.lcdFeedrate.setObjectName("lcdFeedrate")
        self.lcdFilament = QtWidgets.QLCDNumber(self.boxSetTarget)
        self.lcdFilament.setGeometry(QtCore.QRect(90, 20, 120, 100))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdFilament.setFont(font)
        self.lcdFilament.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdFilament.setAutoFillBackground(True)
        self.lcdFilament.setSmallDecimalPoint(False)
        self.lcdFilament.setDigitCount(5)
        self.lcdFilament.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdFilament.setProperty("value", 1.75)
        self.lcdFilament.setObjectName("lcdFilament")
        self.lcdcoldblock = QtWidgets.QLCDNumber(self.boxSetTarget)
        self.lcdcoldblock.setGeometry(QtCore.QRect(90, 240, 120, 100))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdcoldblock.setFont(font)
        self.lcdcoldblock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdcoldblock.setAutoFillBackground(True)
        self.lcdcoldblock.setSmallDecimalPoint(False)
        self.lcdcoldblock.setDigitCount(5)
        self.lcdcoldblock.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdcoldblock.setProperty("value", 25.1)
        self.lcdcoldblock.setObjectName("lcdcoldblock")
        self.lcdAircon = QtWidgets.QLCDNumber(self.boxSetTarget)
        self.lcdAircon.setGeometry(QtCore.QRect(90, 130, 120, 100))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdAircon.setFont(font)
        self.lcdAircon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdAircon.setAutoFillBackground(True)
        self.lcdAircon.setSmallDecimalPoint(False)
        self.lcdAircon.setDigitCount(5)
        self.lcdAircon.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdAircon.setProperty("value", 25.1)
        self.lcdAircon.setObjectName("lcdAircon")
        self.lcdHotend = QtWidgets.QLCDNumber(self.boxSetTarget)
        self.lcdHotend.setGeometry(QtCore.QRect(90, 350, 120, 100))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdHotend.setFont(font)
        self.lcdHotend.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdHotend.setAutoFillBackground(True)
        self.lcdHotend.setSmallDecimalPoint(False)
        self.lcdHotend.setDigitCount(5)
        self.lcdHotend.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdHotend.setProperty("value", 25.1)
        self.lcdHotend.setObjectName("lcdHotend")
        self.scrollFeedrate = QtWidgets.QScrollBar(self.boxSetTarget)
        self.scrollFeedrate.setGeometry(QtCore.QRect(220, 460, 40, 100))
        self.scrollFeedrate.setAutoFillBackground(False)
        self.scrollFeedrate.setMinimum(1)
        self.scrollFeedrate.setMaximum(50)
        self.scrollFeedrate.setPageStep(1)
        self.scrollFeedrate.setProperty("value", 5)
        self.scrollFeedrate.setSliderPosition(5)
        self.scrollFeedrate.setOrientation(QtCore.Qt.Vertical)
        self.scrollFeedrate.setInvertedAppearance(False)
        self.scrollFeedrate.setInvertedControls(True)
        self.scrollFeedrate.setObjectName("scrollFeedrate")
        self.scrollHotend = QtWidgets.QScrollBar(self.boxSetTarget)
        self.scrollHotend.setGeometry(QtCore.QRect(220, 350, 40, 100))
        self.scrollHotend.setAutoFillBackground(False)
        self.scrollHotend.setMinimum(251)
        self.scrollHotend.setMaximum(1500)
        self.scrollHotend.setPageStep(1)
        self.scrollHotend.setSliderPosition(251)
        self.scrollHotend.setOrientation(QtCore.Qt.Vertical)
        self.scrollHotend.setInvertedAppearance(False)
        self.scrollHotend.setInvertedControls(True)
        self.scrollHotend.setObjectName("scrollHotend")
        self.scrollColdblock = QtWidgets.QScrollBar(self.boxSetTarget)
        self.scrollColdblock.setGeometry(QtCore.QRect(220, 240, 40, 100))
        self.scrollColdblock.setAutoFillBackground(False)
        self.scrollColdblock.setMinimum(150)
        self.scrollColdblock.setMaximum(300)
        self.scrollColdblock.setPageStep(1)
        self.scrollColdblock.setSliderPosition(251)
        self.scrollColdblock.setOrientation(QtCore.Qt.Vertical)
        self.scrollColdblock.setInvertedAppearance(False)
        self.scrollColdblock.setInvertedControls(True)
        self.scrollColdblock.setObjectName("scrollColdblock")
        self.scrollAircon = QtWidgets.QScrollBar(self.boxSetTarget)
        self.scrollAircon.setGeometry(QtCore.QRect(220, 130, 40, 100))
        self.scrollAircon.setAutoFillBackground(False)
        self.scrollAircon.setMinimum(150)
        self.scrollAircon.setMaximum(300)
        self.scrollAircon.setPageStep(1)
        self.scrollAircon.setSliderPosition(251)
        self.scrollAircon.setOrientation(QtCore.Qt.Vertical)
        self.scrollAircon.setInvertedAppearance(False)
        self.scrollAircon.setInvertedControls(True)
        self.scrollAircon.setObjectName("scrollAircon")
        self.scrollFilament = QtWidgets.QScrollBar(self.boxSetTarget)
        self.scrollFilament.setGeometry(QtCore.QRect(220, 20, 40, 100))
        self.scrollFilament.setAutoFillBackground(False)
        self.scrollFilament.setMinimum(160)
        self.scrollFilament.setMaximum(210)
        self.scrollFilament.setPageStep(1)
        self.scrollFilament.setSliderPosition(175)
        self.scrollFilament.setOrientation(QtCore.Qt.Vertical)
        self.scrollFilament.setInvertedAppearance(False)
        self.scrollFilament.setInvertedControls(True)
        self.scrollFilament.setObjectName("scrollFilament")
        self.btnONAircon = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnONAircon.setGeometry(QtCore.QRect(260, 140, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnONAircon.setFont(font)
        self.btnONAircon.setObjectName("btnONAircon")
        self.btnRetract = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnRetract.setGeometry(QtCore.QRect(170, 570, 140, 120))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btnRetract.setFont(font)
        self.btnRetract.setObjectName("btnRetract")
        self.btnExtrude = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnExtrude.setGeometry(QtCore.QRect(10, 570, 140, 120))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btnExtrude.setFont(font)
        self.btnExtrude.setAutoDefault(False)
        self.btnExtrude.setDefault(False)
        self.btnExtrude.setFlat(False)
        self.btnExtrude.setObjectName("btnExtrude")
        self.btnOFFAircon = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnOFFAircon.setGeometry(QtCore.QRect(260, 180, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnOFFAircon.setFont(font)
        self.btnOFFAircon.setObjectName("btnOFFAircon")
        self.btnONColdblock = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnONColdblock.setGeometry(QtCore.QRect(260, 250, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnONColdblock.setFont(font)
        self.btnONColdblock.setObjectName("btnONColdblock")
        self.btnOFFColdblock = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnOFFColdblock.setGeometry(QtCore.QRect(260, 290, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnOFFColdblock.setFont(font)
        self.btnOFFColdblock.setObjectName("btnOFFColdblock")
        self.btnONHotend = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnONHotend.setGeometry(QtCore.QRect(260, 360, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnONHotend.setFont(font)
        self.btnONHotend.setObjectName("btnONHotend")
        self.btnOFFHotend = QtWidgets.QPushButton(self.boxSetTarget)
        self.btnOFFHotend.setGeometry(QtCore.QRect(260, 400, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnOFFHotend.setFont(font)
        self.btnOFFHotend.setObjectName("btnOFFHotend")
        self.boxSensersReading = QtWidgets.QGroupBox(self.ControlTab)
        self.boxSensersReading.setGeometry(QtCore.QRect(320, 0, 151, 461))
        self.boxSensersReading.setObjectName("boxSensersReading")
        self.labelReadAircon = QtWidgets.QLabel(self.boxSensersReading)
        self.labelReadAircon.setGeometry(QtCore.QRect(30, 160, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.labelReadAircon.setFont(font)
        self.labelReadAircon.setAlignment(QtCore.Qt.AlignCenter)
        self.labelReadAircon.setObjectName("labelReadAircon")
        self.labelReadColdblock = QtWidgets.QLabel(self.boxSensersReading)
        self.labelReadColdblock.setGeometry(QtCore.QRect(30, 270, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.labelReadColdblock.setFont(font)
        self.labelReadColdblock.setAlignment(QtCore.Qt.AlignCenter)
        self.labelReadColdblock.setObjectName("labelReadColdblock")
        self.labelReadHotend = QtWidgets.QLabel(self.boxSensersReading)
        self.labelReadHotend.setGeometry(QtCore.QRect(30, 380, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.labelReadHotend.setFont(font)
        self.labelReadHotend.setAlignment(QtCore.Qt.AlignCenter)
        self.labelReadHotend.setObjectName("labelReadHotend")
        self.tabMenu.addTab(self.ControlTab, "")
        self.CameraTab = QtWidgets.QWidget()
        self.CameraTab.setObjectName("CameraTab")
        self.boxOutputfilament = QtWidgets.QGroupBox(self.CameraTab)
        self.boxOutputfilament.setGeometry(QtCore.QRect(0, 0, 241, 261))
        self.boxOutputfilament.setObjectName("boxOutputfilament")
        self.labelOutputDia1 = QtWidgets.QLabel(self.boxOutputfilament)
        self.labelOutputDia1.setGeometry(QtCore.QRect(10, 30, 80, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelOutputDia1.setFont(font)
        self.labelOutputDia1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOutputDia1.setWordWrap(True)
        self.labelOutputDia1.setObjectName("labelOutputDia1")
        self.lcdOutputDia1 = QtWidgets.QLCDNumber(self.boxOutputfilament)
        self.lcdOutputDia1.setGeometry(QtCore.QRect(99, 20, 121, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdOutputDia1.setFont(font)
        self.lcdOutputDia1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdOutputDia1.setAutoFillBackground(True)
        self.lcdOutputDia1.setSmallDecimalPoint(False)
        self.lcdOutputDia1.setDigitCount(5)
        self.lcdOutputDia1.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdOutputDia1.setProperty("value", 0.5)
        self.lcdOutputDia1.setObjectName("lcdOutputDia1")
        self.labelOutputDia2 = QtWidgets.QLabel(self.boxOutputfilament)
        self.labelOutputDia2.setGeometry(QtCore.QRect(11, 110, 80, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelOutputDia2.setFont(font)
        self.labelOutputDia2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOutputDia2.setWordWrap(True)
        self.labelOutputDia2.setObjectName("labelOutputDia2")
        self.lcdOutputDia2 = QtWidgets.QLCDNumber(self.boxOutputfilament)
        self.lcdOutputDia2.setGeometry(QtCore.QRect(100, 100, 121, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdOutputDia2.setFont(font)
        self.lcdOutputDia2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdOutputDia2.setAutoFillBackground(True)
        self.lcdOutputDia2.setSmallDecimalPoint(False)
        self.lcdOutputDia2.setDigitCount(5)
        self.lcdOutputDia2.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdOutputDia2.setProperty("value", 0.5)
        self.lcdOutputDia2.setObjectName("lcdOutputDia2")
        self.lcdOutputDia3 = QtWidgets.QLCDNumber(self.boxOutputfilament)
        self.lcdOutputDia3.setGeometry(QtCore.QRect(99, 180, 121, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdOutputDia3.setFont(font)
        self.lcdOutputDia3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdOutputDia3.setAutoFillBackground(True)
        self.lcdOutputDia3.setSmallDecimalPoint(False)
        self.lcdOutputDia3.setDigitCount(5)
        self.lcdOutputDia3.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdOutputDia3.setProperty("value", 0.5)
        self.lcdOutputDia3.setObjectName("lcdOutputDia3")
        self.labelOutputDia3 = QtWidgets.QLabel(self.boxOutputfilament)
        self.labelOutputDia3.setGeometry(QtCore.QRect(10, 190, 80, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelOutputDia3.setFont(font)
        self.labelOutputDia3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOutputDia3.setWordWrap(True)
        self.labelOutputDia3.setObjectName("labelOutputDia3")
        self.boxCameraview = QtWidgets.QGroupBox(self.CameraTab)
        self.boxCameraview.setGeometry(QtCore.QRect(0, 260, 241, 431))
        self.boxCameraview.setObjectName("boxCameraview")
        self.labelCameraview = QtWidgets.QLabel(self.boxCameraview)
        self.labelCameraview.setGeometry(QtCore.QRect(5, 20, 225, 400))
        self.labelCameraview.setText("")
        self.labelCameraview.setPixmap(QtGui.QPixmap("../../../../../Public/Pictures/Sample Pictures/Koala.jpg"))
        self.labelCameraview.setScaledContents(True)
        self.labelCameraview.setObjectName("labelCameraview")
        self.boxCameracontol = QtWidgets.QGroupBox(self.CameraTab)
        self.boxCameracontol.setGeometry(QtCore.QRect(250, 0, 221, 691))
        self.boxCameracontol.setObjectName("boxCameracontol")
        self.spinCameralight = QtWidgets.QSpinBox(self.boxCameracontol)
        self.spinCameralight.setGeometry(QtCore.QRect(100, 20, 111, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.spinCameralight.setFont(font)
        self.spinCameralight.setMaximum(255)
        self.spinCameralight.setSingleStep(5)
        self.spinCameralight.setProperty("value", 125)
        self.spinCameralight.setObjectName("spinCameralight")
        self.labelCameralight = QtWidgets.QLabel(self.boxCameracontol)
        self.labelCameralight.setGeometry(QtCore.QRect(10, 20, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelCameralight.setFont(font)
        self.labelCameralight.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCameralight.setWordWrap(True)
        self.labelCameralight.setObjectName("labelCameralight")
        self.labelLinelength = QtWidgets.QLabel(self.boxCameracontol)
        self.labelLinelength.setGeometry(QtCore.QRect(10, 200, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelLinelength.setFont(font)
        self.labelLinelength.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLinelength.setWordWrap(True)
        self.labelLinelength.setObjectName("labelLinelength")
        self.labelEdgesigma = QtWidgets.QLabel(self.boxCameracontol)
        self.labelEdgesigma.setGeometry(QtCore.QRect(10, 110, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelEdgesigma.setFont(font)
        self.labelEdgesigma.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdgesigma.setWordWrap(True)
        self.labelEdgesigma.setObjectName("labelEdgesigma")
        self.spinEdgesigma = QtWidgets.QDoubleSpinBox(self.boxCameracontol)
        self.spinEdgesigma.setGeometry(QtCore.QRect(100, 110, 111, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.spinEdgesigma.setFont(font)
        self.spinEdgesigma.setMinimum(1.0)
        self.spinEdgesigma.setProperty("value", 33.0)
        self.spinEdgesigma.setObjectName("spinEdgesigma")
        self.btnCamera = QtWidgets.QPushButton(self.boxCameracontol)
        self.btnCamera.setGeometry(QtCore.QRect(20, 500, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnCamera.setFont(font)
        self.btnCamera.setObjectName("btnCamera")
        self.spinLinelength = QtWidgets.QSpinBox(self.boxCameracontol)
        self.spinLinelength.setGeometry(QtCore.QRect(100, 201, 111, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.spinLinelength.setFont(font)
        self.spinLinelength.setMaximum(1000)
        self.spinLinelength.setSingleStep(1)
        self.spinLinelength.setProperty("value", 500)
        self.spinLinelength.setObjectName("spinLinelength")
        self.spinLinegap = QtWidgets.QSpinBox(self.boxCameracontol)
        self.spinLinegap.setGeometry(QtCore.QRect(100, 291, 111, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.spinLinegap.setFont(font)
        self.spinLinegap.setMaximum(1000)
        self.spinLinegap.setSingleStep(1)
        self.spinLinegap.setProperty("value", 300)
        self.spinLinegap.setObjectName("spinLinegap")
        self.labelLinegap = QtWidgets.QLabel(self.boxCameracontol)
        self.labelLinegap.setGeometry(QtCore.QRect(10, 290, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelLinegap.setFont(font)
        self.labelLinegap.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLinegap.setWordWrap(True)
        self.labelLinegap.setObjectName("labelLinegap")
        self.labelCameraP = QtWidgets.QLabel(self.boxCameracontol)
        self.labelCameraP.setGeometry(QtCore.QRect(20, 380, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelCameraP.setFont(font)
        self.labelCameraP.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCameraP.setWordWrap(True)
        self.labelCameraP.setObjectName("labelCameraP")
        self.spinCameraP = QtWidgets.QDoubleSpinBox(self.boxCameracontol)
        self.spinCameraP.setGeometry(QtCore.QRect(100, 380, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinCameraP.setFont(font)
        self.spinCameraP.setMinimum(0.0)
        self.spinCameraP.setSingleStep(0.1)
        self.spinCameraP.setProperty("value", 5.0)
        self.spinCameraP.setObjectName("spinCameraP")
        self.labelCameraI = QtWidgets.QLabel(self.boxCameracontol)
        self.labelCameraI.setGeometry(QtCore.QRect(20, 420, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelCameraI.setFont(font)
        self.labelCameraI.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCameraI.setWordWrap(True)
        self.labelCameraI.setObjectName("labelCameraI")
        self.spinCameraI = QtWidgets.QDoubleSpinBox(self.boxCameracontol)
        self.spinCameraI.setGeometry(QtCore.QRect(100, 420, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinCameraI.setFont(font)
        self.spinCameraI.setMinimum(0.0)
        self.spinCameraI.setSingleStep(0.1)
        self.spinCameraI.setProperty("value", 0.0)
        self.spinCameraI.setObjectName("spinCameraI")
        self.spinCameraD = QtWidgets.QDoubleSpinBox(self.boxCameracontol)
        self.spinCameraD.setGeometry(QtCore.QRect(100, 460, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinCameraD.setFont(font)
        self.spinCameraD.setMinimum(0.0)
        self.spinCameraD.setSingleStep(0.1)
        self.spinCameraD.setProperty("value", 0.0)
        self.spinCameraD.setObjectName("spinCameraD")
        self.labelCameraD = QtWidgets.QLabel(self.boxCameracontol)
        self.labelCameraD.setGeometry(QtCore.QRect(20, 460, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelCameraD.setFont(font)
        self.labelCameraD.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCameraD.setWordWrap(True)
        self.labelCameraD.setObjectName("labelCameraD")
        self.btnCameraPID = QtWidgets.QPushButton(self.boxCameracontol)
        self.btnCameraPID.setGeometry(QtCore.QRect(120, 500, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnCameraPID.setFont(font)
        self.btnCameraPID.setObjectName("btnCameraPID")
        self.textBrowser = QtWidgets.QTextBrowser(self.boxCameracontol)
        self.textBrowser.setGeometry(QtCore.QRect(20, 590, 191, 91))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.tabMenu.addTab(self.CameraTab, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setEnabled(False)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabMenu.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnEstop.setText(_translate("MainWindow", "E-Stop"))
        self.boxSetTarget.setTitle(_translate("MainWindow", "User Input and Set Target"))
        self.labelFilament.setText(_translate("MainWindow", "Filament Diameter"))
        self.labelAircon.setText(_translate("MainWindow", "Aircon"))
        self.labelColdblock.setText(_translate("MainWindow", "ColdBlock"))
        self.labelHotend.setText(_translate("MainWindow", "HotEnd"))
        self.labelFeedrate.setText(_translate("MainWindow", "Feedrate"))
        self.btnONAircon.setText(_translate("MainWindow", "On"))
        self.btnRetract.setText(_translate("MainWindow", "Retract"))
        self.btnExtrude.setText(_translate("MainWindow", "Extrude"))
        self.btnOFFAircon.setText(_translate("MainWindow", "Off"))
        self.btnONColdblock.setText(_translate("MainWindow", "On"))
        self.btnOFFColdblock.setText(_translate("MainWindow", "Off"))
        self.btnONHotend.setText(_translate("MainWindow", "On"))
        self.btnOFFHotend.setText(_translate("MainWindow", "Off"))
        self.boxSensersReading.setTitle(_translate("MainWindow", "Sensors Reading"))
        self.labelReadAircon.setText(_translate("MainWindow", "30.0C"))
        self.labelReadColdblock.setText(_translate("MainWindow", "30.0C"))
        self.labelReadHotend.setText(_translate("MainWindow", "30.0C"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.ControlTab), _translate("MainWindow", "Control"))
        self.boxOutputfilament.setTitle(_translate("MainWindow", "Output Filament"))
        self.labelOutputDia1.setText(_translate("MainWindow", "Reading 1"))
        self.labelOutputDia2.setText(_translate("MainWindow", "Reading 2"))
        self.labelOutputDia3.setText(_translate("MainWindow", "Reading 3"))
        self.boxCameraview.setTitle(_translate("MainWindow", "Camera View"))
        self.boxCameracontol.setTitle(_translate("MainWindow", "Camera Control"))
        self.labelCameralight.setText(_translate("MainWindow", "Camera Light"))
        self.labelLinelength.setText(_translate("MainWindow", "Line Length"))
        self.labelEdgesigma.setText(_translate("MainWindow", "Edge Detection Sigma"))
        self.btnCamera.setText(_translate("MainWindow", "Camera On"))
        self.labelLinegap.setText(_translate("MainWindow", "Line Gap"))
        self.labelCameraP.setText(_translate("MainWindow", "P-Term"))
        self.labelCameraI.setText(_translate("MainWindow", "I-Term"))
        self.labelCameraD.setText(_translate("MainWindow", "D-Term"))
        self.btnCameraPID.setText(_translate("MainWindow", "PID Enable"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">NULL Data</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.CameraTab), _translate("MainWindow", "Camera"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

